services:
  mongodb:
    image: mongo:7
    container_name: ai-agent-nodejs-lab-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ai_ticket_classifier
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: ai-agent-nodejs-lab-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
